.PHONY: clean All

All:
	@echo "----------Building project:[ Chanlleage - Debug ]----------"
	@cd "Chanlleage" && "$(MAKE)" -f  "Chanlleage.mk"
clean:
	@echo "----------Cleaning project:[ Chanlleage - Debug ]----------"
	@cd "Chanlleage" && "$(MAKE)" -f  "Chanlleage.mk" clean
